exports.countryOptions = [
    {"value":"AF", "label":"Afghanistan"},
    {"value":"AX", "label":"Åland Islands"},
    {"value":"AL", "label":"Albania"},
    {"value":"DZ", "label":"Algeria"},
    {"value":"AS", "label":"American Samoa"},
    {"value":"AD", "label":"Andorra"},
    {"value":"AO", "label":"Angola"},
    {"value":"AI", "label":"Anguilla"},
    {"value":"AQ", "label":"Antarctica"},
    {"value":"AG", "label":"Antigua and Barbuda"},
    {"value":"AR", "label":"Argentina"},
    {"value":"AM", "label":"Armenia"},
    {"value":"AW", "label":"Aruba"},
    {"value":"AU", "label":"Australia"},
    {"value":"AT", "label":"Austria"},
    {"value":"AZ", "label":"Azerbaijan"},
    {"value":"BS", "label":"Bahamas"},
    {"value":"BH", "label":"Bahrain"},
    {"value":"BD", "label":"Bangladesh"},
    {"value":"BB", "label":"Barbados"},
    {"value":"BY", "label":"Belarus"},
    {"value":"BE", "label":"Belgium"},
    {"value":"BZ", "label":"Belize"},
    {"value":"BJ", "label":"Benin"},
    {"value":"BM", "label":"Bermuda"},
    {"value":"BT", "label":"Bhutan"},
    {"value":"BO", "label":"Bolivia"},
    {"value":"BA", "label":"Bosnia and Herzegovina"},
    {"value":"BW", "label":"Botswana"},
    {"value":"BV", "label":"Bouvet Island"},
    {"value":"BR", "label":"Brazil"},
    {"value":"IO", "label":"British Indian Ocean Territory"},
    {"value":"BN", "label":"Brunei Darussalam"},
    {"value":"BG", "label":"Bulgaria"},
    {"value":"BF", "label":"Burkina Faso"},
    {"value":"BI", "label":"Burundi"},
    {"value":"KH", "label":"Cambodia"},
    {"value":"CM", "label":"Cameroon"},
    {"value":"CA", "label":"Canada"},
    {"value":"CV", "label":"Cape Verde"},
    {"value":"KY", "label":"Cayman Islands"},
    {"value":"CF", "label":"Central African Republic"},
    {"value":"TD", "label":"Chad"},
    {"value":"CL", "label":"Chile"},
    {"value":"CN", "label":"China"},
    {"value":"CX", "label":"Christmas Island"},
    {"value":"CC", "label":"Cocos (Keeling) Islands"},
    {"value":"CO", "label":"Colombia"},
    {"value":"KM", "label":"Comoros"},
    {"value":"CG", "label":"Congo"},
    {"value":"CD", "label":"Congo, The Democratic Republic of the"},
    {"value":"CK", "label":"Cook Islands"},
    {"value":"CR", "label":"Costa Rica"},
    {"value":"CI", "label":"Cote D'Ivoire"},
    {"value":"HR", "label":"Croatia"},
    {"value":"CU", "label":"Cuba"},
    {"value":"CY", "label":"Cyprus"},
    {"value":"CZ", "label":"Czech Republic"},
    {"value":"DK", "label":"Denmark"},
    {"value":"DJ", "label":"Djibouti"},
    {"value":"DM", "label":"Dominica"},
    {"value":"DO", "label":"Dominican Republic"},
    {"value":"EC", "label":"Ecuador"},
    {"value":"EG", "label":"Egypt"},
    {"value":"SV", "label":"El Salvador"},
    {"value":"GQ", "label":"Equatorial Guinea"},
    {"value":"ER", "label":"Eritrea"},
    {"value":"EE", "label":"Estonia"},
    {"value":"ET", "label":"Ethiopia"},
    {"value":"FK", "label":"Falkland Islands (Malvinas)"},
    {"value":"FO", "label":"Faroe Islands"},
    {"value":"FJ", "label":"Fiji"},
    {"value":"FI", "label":"Finland"},
    {"value":"FR", "label":"France"},
    {"value":"GF", "label":"French Guiana"},
    {"value":"PF", "label":"French Polynesia"},
    {"value":"TF", "label":"French Southern Territories"},
    {"value":"GA", "label":"Gabon"},
    {"value":"GM", "label":"Gambia"},
    {"value":"GE", "label":"Georgia"},
    {"value":"DE", "label":"Germany"},
    {"value":"GH", "label":"Ghana"},
    {"value":"GI", "label":"Gibraltar"},
    {"value":"GR", "label":"Greece"},
    {"value":"GL", "label":"Greenland"},
    {"value":"GD", "label":"Grenada"},
    {"value":"GP", "label":"Guadeloupe"},
    {"value":"GU", "label":"Guam"},
    {"value":"GT", "label":"Guatemala"},
    {"value":"GG", "label":"Guernsey"},
    {"value":"GN", "label":"Guinea"},
    {"value":"GW", "label":"Guinea-Bissau"},
    {"value":"GY", "label":"Guyana"},
    {"value":"HT", "label":"Haiti"},
    {"value":"HM", "label":"Heard Island and Mcdonald Islands"},
    {"value":"VA", "label":"Holy See (Vatican City State)"},
    {"value":"HN", "label":"Honduras"},
    {"value":"HK", "label":"Hong Kong"},
    {"value":"HU", "label":"Hungary"},
    {"value":"IS", "label":"Iceland"},
    {"value":"IN", "label":"India"},
    {"value":"ID", "label":"Indonesia"},
    {"value":"IR", "label":"Iran, Islamic Republic Of"},
    {"value":"IQ", "label":"Iraq"},
    {"value":"IE", "label":"Ireland"},
    {"value":"IM", "label":"Isle of Man"},
    {"value":"IL", "label":"Israel"},
    {"value":"IT", "label":"Italy"},
    {"value":"JM", "label":"Jamaica"},
    {"value":"JP", "label":"Japan"},
    {"value":"JE", "label":"Jersey"},
    {"value":"JO", "label":"Jordan"},
    {"value":"KZ", "label":"Kazakhstan"},
    {"value":"KE", "label":"Kenya"},
    {"value":"KI", "label":"Kiribati"},
    {"value":"KP", "label":"Korea, Democratic People's Republic of"},
    {"value":"KR", "label":"Korea, Republic of"},
    {"value":"XK", "label":"Kosovo"},
    {"value":"KW", "label":"Kuwait"},
    {"value":"KG", "label":"Kyrgyzstan"},
    {"value":"LA", "label":"Lao People's Democratic Republic"},
    {"value":"LV", "label":"Latvia"},
    {"value":"LB", "label":"Lebanon"},
    {"value":"LS", "label":"Lesotho"},
    {"value":"LR", "label":"Liberia"},
    {"value":"LY", "label":"Libyan Arab Jamahiriya"},
    {"value":"LI", "label":"Liechtenstein"},
    {"value":"LT", "label":"Lithuania"},
    {"value":"LU", "label":"Luxembourg"},
    {"value":"MO", "label":"Macao"},
    {"value":"MK", "label":"Macedonia, The Former Yugoslav Republic of"},
    {"value":"MG", "label":"Madagascar"},
    {"value":"MW", "label":"Malawi"},
    {"value":"MY", "label":"Malaysia"},
    {"value":"MV", "label":"Maldives"},
    {"value":"ML", "label":"Mali"},
    {"value":"MT", "label":"Malta"},
    {"value":"MH", "label":"Marshall Islands"},
    {"value":"MQ", "label":"Martinique"},
    {"value":"MR", "label":"Mauritania"},
    {"value":"MU", "label":"Mauritius"},
    {"value":"YT", "label":"Mayotte"},
    {"value":"MX", "label":"Mexico"},
    {"value":"FM", "label":"Micronesia, Federated States of"},
    {"value":"MD", "label":"Moldova, Republic of"},
    {"value":"MC", "label":"Monaco"},
    {"value":"MN", "label":"Mongolia"},
    {"value":'ME', "label":"Montenegro" },
    {"value":"MS", "label":"Montserrat"},
    {"value":"MA", "label":"Morocco"},
    {"value":"MZ", "label":"Mozambique"},
    {"value":"MM", "label":"Myanmar"},
    {"value":"NA", "label":"Namibia"},
    {"value":"NR", "label":"Nauru"},
    {"value":"NP", "label":"Nepal"},
    {"value":"NL", "label":"Netherlands"},
    {"value":"AN", "label":"Netherlands Antilles"},
    {"value":"NC", "label":"New Caledonia"},
    {"value":"NZ", "label":"New Zealand"},
    {"value":"NI", "label":"Nicaragua"},
    {"value":"NE", "label":"Niger"},
    {"value":"NG", "label":"Nigeria"},
    {"value":"NU", "label":"Niue"},
    {"value":"NF", "label":"Norfolk Island"},
    {"value":"MP", "label":"Northern Mariana Islands"},
    {"value":"NO", "label":"Norway"},
    {"value":"OM", "label":"Oman"},
    {"value":"PK", "label":"Pakistan"},
    {"value":"PW", "label":"Palau"},
    {"value":"PS", "label":"Palestinian Territory, Occupied"},
    {"value":"PA", "label":"Panama"},
    {"value":"PG", "label":"Papua New Guinea"},
    {"value":"PY", "label":"Paraguay"},
    {"value":"PE", "label":"Peru"},
    {"value":"PH", "label":"Philippines"},
    {"value":"PN", "label":"Pitcairn"},
    {"value":"PL", "label":"Poland"},
    {"value":"PT", "label":"Portugal"},
    {"value":"PR", "label":"Puerto Rico"},
    {"value":"QA", "label":"Qatar"},
    {"value":"RE", "label":"Reunion"},
    {"value":"RO", "label":"Romania"},
    {"value":"RU", "label":"Russian Federation"},
    {"value":"RW", "label":"Rwanda"},
    {"value":"SH", "label":"Saint Helena"},
    {"value":"KN", "label":"Saint Kitts and Nevis"},
    {"value":"LC", "label":"Saint Lucia"},
    {"value":"PM", "label":"Saint Pierre and Miquelon"},
    {"value":"VC", "label":"Saint Vincent and the Grenadines"},
    {"value":"WS", "label":"Samoa"},
    {"value":"SM", "label":"San Marino"},
    {"value":"ST", "label":"Sao Tome and Principe"},
    {"value":"SA", "label":"Saudi Arabia"},
    {"value":"SN", "label":"Senegal"},
    // {"value":"CS", "label":"Serbia and Montenegro"},
    {"value":"RS", "label":"Serbia"},
    {"value":"SC", "label":"Seychelles"},
    {"value":"SL", "label":"Sierra Leone"},
    {"value":"SG", "label":"Singapore"},
    {"value":"SK", "label":"Slovakia"},
    {"value":"SI", "label":"Slovenia"},
    {"value":"SB", "label":"Solomon Islands"},
    {"value":"SO", "label":"Somalia"},
    {"value":"ZA", "label":"South Africa"},
    {"value":"GS", "label":"South Georgia and the South Sandwich Islands"},
    {"value":"ES", "label":"Spain"},
    {"value":"LK", "label":"Sri Lanka"},
    {"value":"SD", "label":"Sudan"},
    {"value":"SR", "label":"Surilabel"},
    {"value":"SJ", "label":"Svalbard and Jan Mayen"},
    {"value":"SZ", "label":"Swaziland"},
    {"value":"SE", "label":"Sweden"},
    {"value":"CH", "label":"Switzerland"},
    {"value":"SY", "label":"Syrian Arab Republic"},
    {"value":"TW", "label":"Taiwan"},
    {"value":"TJ", "label":"Tajikistan"},
    {"value":"TZ", "label":"Tanzania, United Republic of"},
    {"value":"TH", "label":"Thailand"},
    {"value":"TL", "label":"Timor-Leste"},
    {"value":"TG", "label":"Togo"},
    {"value":"TK", "label":"Tokelau"},
    {"value":"TO", "label":"Tonga"},
    {"value":"TT", "label":"Trinidad and Tobago"},
    {"value":"TN", "label":"Tunisia"},
    {"value":"TR", "label":"Turkey"},
    {"value":"TM", "label":"Turkmenistan"},
    {"value":"TC", "label":"Turks and Caicos Islands"},
    {"value":"TV", "label":"Tuvalu"},
    {"value":"UG", "label":"Uganda"},
    {"value":"UA", "label":"Ukraine"},
    {"value":"AE", "label":"United Arab Emirates"},
    {"value":"GB", "label":"United Kingdom"},
    {"value":"US", "label":"United States"},
    {"value":"UM", "label":"United States Minor Outlying Islands"},
    {"value":"UY", "label":"Uruguay"},
    {"value":"UZ", "label":"Uzbekistan"},
    {"value":"VU", "label":"Vanuatu"},
    {"value":"VE", "label":"Venezuela"},
    {"value":"VN", "label":"Vietnam"},
    {"value":"VG", "label":"Virgin Islands, British"},
    {"value":"VI", "label":"Virgin Islands, U.S."},
    {"value":"WF", "label":"Wallis and Futuna"},
    {"value":"EH", "label":"Western Sahara"},
    {"value":"YE", "label":"Yemen"},
    {"value":"ZM", "label":"Zambia"},
    {"value":"ZW", "label":"Zimbabwe"}
];

exports.countryMap = { 
    af: { code: 'af', name: 'Afghanistan' },
    ax: { code: 'ax', name: 'Åland Islands' },
    al: { code: 'al', name: 'Albania' },
    dz: { code: 'dz', name: 'Algeria' },
    as: { code: 'as', name: 'American Samoa' },
    ad: { code: 'ad', name: 'Andorra' },
    ao: { code: 'ao', name: 'Angola' },
    ai: { code: 'ai', name: 'Anguilla' },
    aq: { code: 'aq', name: 'Antarctica' },
    ag: { code: 'ag', name: 'Antigua and Barbuda' },
    ar: { code: 'ar', name: 'Argentina' },
    am: { code: 'am', name: 'Armenia' },
    aw: { code: 'aw', name: 'Aruba' },
    au: { code: 'au', name: 'Australia' },
    at: { code: 'at', name: 'Austria' },
    az: { code: 'az', name: 'Azerbaijan' },
    bs: { code: 'bs', name: 'Bahamas' },
    bh: { code: 'bh', name: 'Bahrain' },
    bd: { code: 'bd', name: 'Bangladesh' },
    bb: { code: 'bb', name: 'Barbados' },
    by: { code: 'by', name: 'Belarus' },
    be: { code: 'be', name: 'Belgium' },
    bz: { code: 'bz', name: 'Belize' },
    bj: { code: 'bj', name: 'Benin' },
    bm: { code: 'bm', name: 'Bermuda' },
    bt: { code: 'bt', name: 'Bhutan' },
    bo: { code: 'bo', name: 'Bolivia' },
    ba: { code: 'ba', name: 'Bosnia and Herzegovina' },
    bw: { code: 'bw', name: 'Botswana' },
    bv: { code: 'bv', name: 'Bouvet Island' },
    br: { code: 'br', name: 'Brazil' },
    io: { code: 'io', name: 'British Indian Ocean Territory' },
    bn: { code: 'bn', name: 'Brunei Darussalam' },
    bg: { code: 'bg', name: 'Bulgaria' },
    bf: { code: 'bf', name: 'Burkina Faso' },
    bi: { code: 'bi', name: 'Burundi' },
    kh: { code: 'kh', name: 'Cambodia' },
    cm: { code: 'cm', name: 'Cameroon' },
    ca: { code: 'ca', name: 'Canada' },
    cv: { code: 'cv', name: 'Cape Verde' },
    ky: { code: 'ky', name: 'Cayman Islands' },
    cf: { code: 'cf', name: 'Central African Republic' },
    td: { code: 'td', name: 'Chad' },
    cl: { code: 'cl', name: 'Chile' },
    cn: { code: 'cn', name: 'China' },
    cx: { code: 'cx', name: 'Christmas Island' },
    cc: { code: 'cc', name: 'Cocos (Keeling) Islands' },
    co: { code: 'co', name: 'Colombia' },
    km: { code: 'km', name: 'Comoros' },
    cg: { code: 'cg', name: 'Congo' },
    cd: { code: 'cd', name: 'Congo, Democratic Republic' },
    ck: { code: 'ck', name: 'Cook Islands' },
    cr: { code: 'cr', name: 'Costa Rica' },
    ci: { code: 'ci', name: 'Cote D\'Ivoire' },
    hr: { code: 'hr', name: 'Croatia' },
    cu: { code: 'cu', name: 'Cuba' },
    cy: { code: 'cy', name: 'Cyprus' },
    cz: { code: 'cz', name: 'Czech Republic' },
    dk: { code: 'dk', name: 'Denmark' },
    dj: { code: 'dj', name: 'Djibouti' },
    dm: { code: 'dm', name: 'Dominica' },
    do: { code: 'do', name: 'Dominican Republic' },
    ec: { code: 'ec', name: 'Ecuador' },
    eg: { code: 'eg', name: 'Egypt' },
    sv: { code: 'sv', name: 'El Salvador' },
    gq: { code: 'gq', name: 'Equatorial Guinea' },
    er: { code: 'er', name: 'Eritrea' },
    ee: { code: 'ee', name: 'Estonia' },
    et: { code: 'et', name: 'Ethiopia' },
    fk: { code: 'fk', name: 'Falkland Islands (Malvinas)' },
    fo: { code: 'fo', name: 'Faroe Islands' },
    fj: { code: 'fj', name: 'Fiji' },
    fi: { code: 'fi', name: 'Finland' },
    fr: { code: 'fr', name: 'France' },
    gf: { code: 'gf', name: 'French Guiana' },
    pf: { code: 'pf', name: 'French Polynesia' },
    tf: { code: 'tf', name: 'French Southern Territories' },
    ga: { code: 'ga', name: 'Gabon' },
    gm: { code: 'gm', name: 'Gambia' },
    ge: { code: 'ge', name: 'Georgia' },
    de: { code: 'de', name: 'Germany' },
    gh: { code: 'gh', name: 'Ghana' },
    gi: { code: 'gi', name: 'Gibraltar' },
    gr: { code: 'gr', name: 'Greece' },
    gl: { code: 'gl', name: 'Greenland' },
    gd: { code: 'gd', name: 'Grenada' },
    gp: { code: 'gp', name: 'Guadeloupe' },
    gu: { code: 'gu', name: 'Guam' },
    gt: { code: 'gt', name: 'Guatemala' },
    gg: { code: 'gg', name: 'Guernsey' },
    gn: { code: 'gn', name: 'Guinea' },
    gw: { code: 'gw', name: 'Guinea-Bissau' },
    gy: { code: 'gy', name: 'Guyana' },
    ht: { code: 'ht', name: 'Haiti' },
    hm: { code: 'hm', name: 'Heard Island and Mcdonald Islands' },
    va: { code: 'va', name: 'Holy See (Vatican City State)' },
    hn: { code: 'hn', name: 'Honduras' },
    hk: { code: 'hk', name: 'Hong Kong' },
    hu: { code: 'hu', name: 'Hungary' },
    is: { code: 'is', name: 'Iceland' },
    in: { code: 'in', name: 'India' },
    id: { code: 'id', name: 'Indonesia' },
    ir: { code: 'ir', name: 'Iran' },
    iq: { code: 'iq', name: 'Iraq' },
    ie: { code: 'ie', name: 'Ireland' },
    im: { code: 'im', name: 'Isle of Man' },
    il: { code: 'il', name: 'Israel' },
    it: { code: 'it', name: 'Italy' },
    jm: { code: 'jm', name: 'Jamaica' },
    jp: { code: 'jp', name: 'Japan' },
    je: { code: 'je', name: 'Jersey' },
    jo: { code: 'jo', name: 'Jordan' },
    kz: { code: 'kz', name: 'Kazakhstan' },
    ke: { code: 'ke', name: 'Kenya' },
    ki: { code: 'ki', name: 'Kiribati' },
    kp: { code: 'kp', name: 'Korea, Democratic People\'s Republic of' },
    kr: { code: 'kr', name: 'Korea, Republic of' },
    xk: { code: 'xk', name: 'Kosovo' },
    kw: { code: 'kw', name: 'Kuwait' },
    kg: { code: 'kg', name: 'Kyrgyzstan' },
    la: { code: 'la', name: 'Lao People\'s Democratic Republic' },
    lv: { code: 'lv', name: 'Latvia' },
    lb: { code: 'lb', name: 'Lebanon' },
    ls: { code: 'ls', name: 'Lesotho' },
    lr: { code: 'lr', name: 'Liberia' },
    ly: { code: 'ly', name: 'Libyan Arab Jamahiriya' },
    li: { code: 'li', name: 'Liechtenstein' },
    lt: { code: 'lt', name: 'Lithuania' },
    lu: { code: 'lu', name: 'Luxembourg' },
    mo: { code: 'mo', name: 'Macao' },
    mk: { code: 'mk', name: 'Macedonia' },
    mg: { code: 'mg', name: 'Madagascar' },
    mw: { code: 'mw', name: 'Malawi' },
    my: { code: 'my', name: 'Malaysia' },
    mv: { code: 'mv', name: 'Maldives' },
    ml: { code: 'ml', name: 'Mali' },
    mt: { code: 'mt', name: 'Malta' },
    mh: { code: 'mh', name: 'Marshall Islands' },
    mq: { code: 'mq', name: 'Martinique' },
    mr: { code: 'mr', name: 'Mauritania' },
    mu: { code: 'mu', name: 'Mauritius' },
    yt: { code: 'yt', name: 'Mayotte' },
    mx: { code: 'mx', name: 'Mexico' },
    fm: { code: 'fm', name: 'Micronesia' },
    md: { code: 'md', name: 'Moldova' },
    mc: { code: 'mc', name: 'Monaco' },
    mn: { code: 'mn', name: 'Mongolia' },
    me: { code: 'me', name: 'Montenegro' },
    ms: { code: 'ms', name: 'Montserrat' },
    ma: { code: 'ma', name: 'Morocco' },
    mz: { code: 'mz', name: 'Mozambique' },
    mm: { code: 'mm', name: 'Myanmar' },
    na: { code: 'na', name: 'Namibia' },
    nr: { code: 'nr', name: 'Nauru' },
    np: { code: 'np', name: 'Nepal' },
    nl: { code: 'nl', name: 'Netherlands' },
    an: { code: 'an', name: 'Netherlands Antilles' },
    nc: { code: 'nc', name: 'New Caledonia' },
    nz: { code: 'nz', name: 'New Zealand' },
    ni: { code: 'ni', name: 'Nicaragua' },
    ne: { code: 'ne', name: 'Niger' },
    ng: { code: 'ng', name: 'Nigeria' },
    nu: { code: 'nu', name: 'Niue' },
    nf: { code: 'nf', name: 'Norfolk Island' },
    mp: { code: 'mp', name: 'Northern Mariana Islands' },
    no: { code: 'no', name: 'Norway' },
    om: { code: 'om', name: 'Oman' },
    pk: { code: 'pk', name: 'Pakistan' },
    pw: { code: 'pw', name: 'Palau' },
    ps: { code: 'ps', name: 'Palestinian Territory, Occupied' },
    pa: { code: 'pa', name: 'Panama' },
    pg: { code: 'pg', name: 'Papua New Guinea' },
    py: { code: 'py', name: 'Paraguay' },
    pe: { code: 'pe', name: 'Peru' },
    ph: { code: 'ph', name: 'Philippines' },
    pn: { code: 'pn', name: 'Pitcairn' },
    pl: { code: 'pl', name: 'Poland' },
    pt: { code: 'pt', name: 'Portugal' },
    pr: { code: 'pr', name: 'Puerto Rico' },
    qa: { code: 'qa', name: 'Qatar' },
    re: { code: 're', name: 'Reunion' },
    ro: { code: 'ro', name: 'Romania' },
    ru: { code: 'ru', name: 'Russian Federation' },
    rw: { code: 'rw', name: 'Rwanda' },
    sh: { code: 'sh', name: 'Saint Helena' },
    kn: { code: 'kn', name: 'Saint Kitts and Nevis' },
    lc: { code: 'lc', name: 'Saint Lucia' },
    pm: { code: 'pm', name: 'Saint Pierre and Miquelon' },
    vc: { code: 'vc', name: 'Saint Vincent and the Grenadines' },
    ws: { code: 'ws', name: 'Samoa' },
    sm: { code: 'sm', name: 'San Marino' },
    st: { code: 'st', name: 'Sao Tome and Principe' },
    sa: { code: 'sa', name: 'Saudi Arabia' },
    sn: { code: 'sn', name: 'Senegal' },
    rs: { code: 'rs', name: 'Serbia' },
    sc: { code: 'sc', name: 'Seychelles' },
    sl: { code: 'sl', name: 'Sierra Leone' },
    sg: { code: 'sg', name: 'Singapore' },
    sk: { code: 'sk', name: 'Slovakia' },
    si: { code: 'si', name: 'Slovenia' },
    sb: { code: 'sb', name: 'Solomon Islands' },
    so: { code: 'so', name: 'Somalia' },
    za: { code: 'za', name: 'South Africa' },
    gs: { code: 'gs', name: 'South Georgia and the South Sandwich Islands' },
    es: { code: 'es', name: 'Spain' },
    lk: { code: 'lk', name: 'Sri Lanka' },
    sd: { code: 'sd', name: 'Sudan' },
    sr: { code: 'sr', name: 'Suriname' },
    sj: { code: 'sj', name: 'Svalbard and Jan Mayen' },
    sz: { code: 'sz', name: 'Swaziland' },
    se: { code: 'se', name: 'Sweden' },
    ch: { code: 'ch', name: 'Switzerland' },
    sy: { code: 'sy', name: 'Syrian Arab Republic' },
    tw: { code: 'tw', name: 'Taiwan, Province of China' },
    tj: { code: 'tj', name: 'Tajikistan' },
    tz: { code: 'tz', name: 'Tanzania' },
    th: { code: 'th', name: 'Thailand' },
    tl: { code: 'tl', name: 'Timor-Leste' },
    tg: { code: 'tg', name: 'Togo' },
    tk: { code: 'tk', name: 'Tokelau' },
    to: { code: 'to', name: 'Tonga' },
    tt: { code: 'tt', name: 'Trinidad and Tobago' },
    tn: { code: 'tn', name: 'Tunisia' },
    tr: { code: 'tr', name: 'Turkey' },
    tm: { code: 'tm', name: 'Turkmenistan' },
    tc: { code: 'tc', name: 'Turks and Caicos Islands' },
    tv: { code: 'tv', name: 'Tuvalu' },
    ug: { code: 'ug', name: 'Uganda' },
    ua: { code: 'ua', name: 'Ukraine' },
    ae: { code: 'ae', name: 'United Arab Emirates' },
    gb: { code: 'gb', name: 'United Kingdom' },
    us: { code: 'us', name: 'United States' },
    um: { code: 'um', name: 'United States Minor Outlying Islands' },
    uy: { code: 'uy', name: 'Uruguay' },
    uz: { code: 'uz', name: 'Uzbekistan' },
    vu: { code: 'vu', name: 'Vanuatu' },
    ve: { code: 've', name: 'Venezuela' },
    vn: { code: 'vn', name: 'Viet Nam' },
    vg: { code: 'vg', name: 'Virgin Islands, British' },
    vi: { code: 'vi', name: 'Virgin Islands, U.S.' },
    wf: { code: 'wf', name: 'Wallis and Futuna' },
    eh: { code: 'eh', name: 'Western Sahara' },
    ye: { code: 'ye', name: 'Yemen' },
    zm: { code: 'zm', name: 'Zambia' },
    zw: { code: 'zw', name: 'Zimbabwe' }
};
